version: '3.8'  # no need for V2

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # for app
      - "15672:15672" # RabbitMQ dashboard

  postgres:
    image: postgres:15
    container_name: documentflow-db
    environment:
      POSTGRES_DB: documentflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: documentflow-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/documentflow
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678

volumes:
  postgres_data:

